CREATE TABLE TB_ITEM
(
   id BIGINT NOT NULL AUTO_INCREMENT,
   title VARCHAR (100) NOT NULL,
   PRIMARY KEY (id)
);
CREATE TABLE TB_REVIEW
(
   id BIGINT NOT NULL AUTO_INCREMENT,
   rating DOUBLE PRECISION NOT NULL,
   item_id INT,   
   PRIMARY KEY (id),
   CONSTRAINT fk_item_id FOREIGN KEY (item_id) 
   REFERENCES TB_ITEM(id)
   
   
);
CREATE TABLE TB_USER
(
   id BIGINT NOT NULL AUTO_INCREMENT, 
   PRIMARY KEY (id)
);
